plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:gitlab_node_prefix: gitlab
keyed_groups:
  - key: tags.gitlab_node_type
    separator: ''
hostnames:
  # List host by name instead of the default public ip
  - tag:Name
compose:
  # Return the public IP address of the box for connection
  # 'public_ip_address' is the correct value here and should not be replaced
  ansible_host: public_ip_address
  ansible_user: ubuntu
