
- name: Wait for GitLab to be available
  uri:
    url: '{{ external_url_sanitised }}/-/readiness'
    validate_certs: false
    timeout: 60
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
  tags: healthcheck

